(function(){
'use strict';
const REV='914_jra_frame_force_min';
const app=document.getElementById('app');
const INPUT_SELECTS={
  grade:['G1','G2','G3','L','OP','特別3勝','特別2勝','特別1勝','3勝','2勝','1勝'],
  surface:['芝','ダート','障害'],
  condition:['定量','別定','ハンデ'],
  age:['2歳','3歳','3歳以上','4歳','4歳以上'],
  sex:['牝馬','混合']
};
const SELECT_ALIASES={surface:{'ダ':'ダート','障':'障害'}};
function selectHtml(name,vals,current){const cur=(SELECT_ALIASES[name]&&SELECT_ALIASES[name][current])||current||'';return `<select name="${name}"><option value=""></option>${vals.map(v=>`<option value="${S.esc(v)}" ${v===cur?'selected':''}>${S.esc(v)}</option>`).join('')}</select>`;}
const modalRoot=document.getElementById('modalRoot');
const S=window.REVStore;
const P=window.REVPrediction;
const ST=window.REVStats;
const RC=window.REVRuleCategories;
const SR=window.REVSearch;
const $=(s,r=document)=>r.querySelector(s);
function unlock(){document.body.style.overflow='auto';document.documentElement.style.overflow='auto';document.body.style.position='static';}
function closeModal(){modalRoot.innerHTML='';unlock();}
function topNav(){return `<section class="hero"><h1>REV-VAN</h1><p>トップ画面は操作ボタンのみ。保存レース一覧と上部メニューは表示しません。</p><div class="homeGrid"><button class="bigBtn" onclick="REVAPP.showInput()">レース情報入力</button><button class="bigBtn blue" onclick="REVAPP.showSearch()">レース情報検索</button><button class="bigBtn light" onclick="REVAPP.rulePage()">予想ルール</button><button class="bigBtn gray" onclick="REVAPP.validationPage()">検証結果</button></div><div class="small">REV: ${REV} / session分離構成</div></section>`;}
function home(){app.innerHTML=topNav();unlock();window.scrollTo(0,0);}
function raceCard(r){const p=P.predictions(r);return `<div class="card raceCard"><div class="raceNo">${S.esc(String(r.raceNo||'').replace('R',''))}<span>R</span></div><div class="raceMain"><div class="split"><div><div class="raceTitle">${S.esc(r.raceName||'(レース名未入力)')}</div><div class="meta">${S.esc(r.date)} ${S.esc(r.place)} / ${S.esc(r.grade)} / ${S.esc(r.surface)}${S.esc(r.distance)} / 判定:${S.esc(p.judge)}</div></div><button class="btn blue" onclick="REVAPP.detail('${S.esc(r.id)}')">開く</button></div><div class="btnRow"><button class="btn gray" onclick="REVAPP.analysis('${S.esc(r.id)}')">予想分析</button><button class="btn light" onclick="REVAPP.showInput('${S.esc(r.id)}')">編集</button><button class="btn red" onclick="REVAPP.askDelete('${S.esc(r.id)}')">削除</button></div></div></div>`;}
function showSearch(){app.innerHTML=SR.formHtml();unlock();window.scrollTo(0,0);}
function searchRun(){SR.run(S.load(), raceCard);}
function inputRow(i,h={}){return `<tr data-row="${i}"><td class="c-no">${i}</td><td class="c-name"><input class="horseNameInput" name="h_name_${i}" maxlength="18" value="${S.esc(h.name)}"></td><td class="c-odds"><input class="oddsInput" name="h_odds_${i}" inputmode="decimal" placeholder="999.9" value="${S.esc(h.odds)}"></td><td class="c-past"><input class="pastInput" name="h_past1_${i}" inputmode="numeric" value="${S.esc(h.past1)}"></td><td class="c-past"><input class="pastInput" name="h_past2_${i}" inputmode="numeric" value="${S.esc(h.past2)}"></td><td class="c-past"><input class="pastInput" name="h_past3_${i}" inputmode="numeric" value="${S.esc(h.past3)}"></td></tr>`;}
function inputRows(horses,head){let rows='';for(let i=1;i<=Math.max(1,head||18);i++)rows+=inputRow(i,horses.find(x=>+x.no===i)||{});return rows;}
function resultFields(r){const x=S.normalizeResult(r.result||{});const finish=(key,label,arr)=>`<div class="resultBlock"><div class="split mini"><b>${label}</b><button class="btn smallBtn" type="button" onclick="REVAPP.addFinish('${key}')">追加</button></div><div id="${key}Box">${(arr.filter(Boolean).length?arr.filter(Boolean):['']).map(v=>`<input name="${key}[]" placeholder="馬番" value="${S.esc(v)}">`).join('')}</div></div>`;const bets=(key,label,arr,base)=>{const use=arr.filter(v=>v.combo||v.pay);const rows=use.length?use:Array.from({length:base},()=>({combo:'',pay:''}));return `<div class="resultBlock"><div class="split mini"><b>${label}</b><button class="btn smallBtn" type="button" onclick="REVAPP.addBet('${key}')">追加</button></div><div id="${key}Box">${rows.map(v=>`<div class="grid2 betRow"><input name="${key}Combo[]" placeholder="決まり目" value="${S.esc(v.combo)}"><input name="${key}Pay[]" placeholder="払戻" value="${S.esc(v.pay)}"></div>`).join('')}</div></div>`};return `<div class="grid3">${finish('firsts','1着 馬番',x.firsts)}${finish('seconds','2着 馬番',x.seconds)}${finish('thirds','3着 馬番',x.thirds)}</div><div class="small">同着未使用時は各着順1欄のみ。必要な時だけ「追加」で入力欄を増やします。</div>${bets('umarens','馬連（通常1点）',x.umarens,1)}${bets('wides','ワイド（通常3点）',x.wides,3)}${bets('sanrenpukus','3連複（通常1点）',x.sanrenpukus,1)}`;}
function showInput(id){const r=S.normalizeRace(id?S.byId(id):{});app.innerHTML=`<div class="split"><h1>レース情報入力</h1><button class="btn gray" onclick="REVAPP.home()">トップへ</button></div><form id="raceForm" class="card"><div class="grid2"><div class="field"><label>年月日</label><input name="date" type="date" value="${S.esc(r.date)}"></div><div class="field"><label>開催地</label><select name="place">${S.JRA_PLACES.map(p=>`<option ${p===r.place?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label>レース数</label><select name="raceNo">${Array.from({length:12},(_,i)=>`${i+1}R`).map(x=>`<option ${x===r.raceNo?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>レース名</label><input name="raceName" value="${S.esc(r.raceName)}"></div><div class="field"><label>グレード</label>${selectHtml('grade',INPUT_SELECTS.grade,r.grade)}</div><div class="field"><label>馬場</label>${selectHtml('surface',INPUT_SELECTS.surface,r.surface)}</div><div class="field"><label>距離</label><input name="distance" value="${S.esc(r.distance)}" placeholder="例：1600m"></div><div class="field"><label>条件</label>${selectHtml('condition',INPUT_SELECTS.condition,r.condition)}</div><div class="field"><label>年齢</label>${selectHtml('age',INPUT_SELECTS.age,r.age)}</div><div class="field"><label>性別</label>${selectHtml('sex',INPUT_SELECTS.sex,r.sex)}</div><div class="field"><label>頭数</label><input id="headcountInput" name="headcount" type="number" min="1" max="18" value="${S.esc(r.headcount||18)}" readonly><div class="small">行追加・行削除で自動反映</div></div></div><div class="sectionTitle">出馬表・オッズ・前走</div><div class="btnRow"><button class="btn blue" type="button" onclick="REVAPP.addRow()">行追加</button><button class="btn red" type="button" onclick="REVAPP.delRow()">行削除</button></div><div class="small">前走表記順：前走 → 前2 → 前3。横スクロールしても馬番は左側に固定表示。馬名9文字、単勝は小数点1位込みの3桁表示対応。</div><div class="tableWrap horseInputWrap"><table class="horseInputTable"><colgroup><col class="colNo"><col class="colName"><col class="colOdds"><col class="colPast"><col class="colPast"><col class="colPast"></colgroup><thead><tr><th>馬番</th><th>馬名</th><th>単勝</th><th>前走</th><th>前2</th><th>前3</th></tr></thead><tbody id="horseBody">${inputRows(r.horses,r.headcount)}</tbody></table></div><div class="sectionTitle">結果</div>${resultFields(r)}<div class="field"><label>メモ</label><textarea name="memo">${S.esc(r.memo)}</textarea></div><div class="btnRow"><button class="btn" type="button" onclick="REVAPP.confirmInput()">登録</button><button class="btn gray" type="button" onclick="REVAPP.home()">閉じる</button></div></form>`;unlock();}
function addRow(){const body=$('#horseBody'),head=$('#headcountInput');const i=body.children.length+1;if(i>18)return;body.insertAdjacentHTML('beforeend',inputRow(i,{}));head.value=i;}
function delRow(){const body=$('#horseBody'),head=$('#headcountInput');if(body.children.length<=1)return;body.lastElementChild.remove();head.value=body.children.length;}
function addFinish(key){const box=$(`#${key}Box`);if(box)box.insertAdjacentHTML('beforeend',`<input name="${key}[]" placeholder="馬番" value="">`);}
function addBet(key){const box=$(`#${key}Box`);if(box)box.insertAdjacentHTML('beforeend',`<div class="grid2 betRow"><input name="${key}Combo[]" placeholder="決まり目" value=""><input name="${key}Pay[]" placeholder="払戻" value=""></div>`);}
function arrFD(fd,n){return fd.getAll(n).map(v=>String(v??'').trim()).filter(Boolean);}
function betFD(fd,key){const c=fd.getAll(`${key}Combo[]`),p=fd.getAll(`${key}Pay[]`),n=Math.max(c.length,p.length);const out=[];for(let i=0;i<n;i++){const combo=String(c[i]??'').trim(),pay=String(p[i]??'').trim();if(combo||pay)out.push({combo,pay});}return out;}
function formData(){const f=$('#raceForm'),fd=new FormData(f),head=S.int(fd.get('headcount'))||$('#horseBody').children.length||18,horses=[];for(let i=1;i<=head;i++){const h={no:i,name:fd.get(`h_name_${i}`)||'',odds:fd.get(`h_odds_${i}`)||'',past3:fd.get(`h_past3_${i}`)||'',past2:fd.get(`h_past2_${i}`)||'',past1:fd.get(`h_past1_${i}`)||''};if(h.name||h.odds||h.past3||h.past2||h.past1)horses.push(h);}return P.recalc({date:fd.get('date'),place:fd.get('place'),raceNo:fd.get('raceNo'),raceName:fd.get('raceName'),grade:fd.get('grade'),surface:fd.get('surface'),distance:fd.get('distance'),condition:fd.get('condition'),age:fd.get('age'),sex:fd.get('sex'),headcount:head,horses,result:{firsts:arrFD(fd,'firsts[]'),seconds:arrFD(fd,'seconds[]'),thirds:arrFD(fd,'thirds[]'),umarens:betFD(fd,'umarens'),wides:betFD(fd,'wides'),sanrenpukus:betFD(fd,'sanrenpukus')},memo:fd.get('memo')});}
function summaryHtml(r){return `<div class="card"><h2>${S.esc(r.date)} ${S.esc(r.place)} ${S.esc(r.raceNo)}</h2><div class="raceTitle">${S.esc(r.raceName)}</div><div class="meta">${S.esc(r.grade)} / ${S.esc(r.surface)}${S.esc(r.distance)} / ${S.esc(r.condition)} / ${S.esc(r.age)} / ${S.esc(r.sex)} / ${S.esc(r.headcount)}頭</div><div class="small">出馬表 ${r.horses.length}頭 / 印 ${r.horses.filter(h=>h.mark).map(h=>h.mark+h.no).join(' ')||'なし'}</div></div>`;}
function confirmInput(){const r=formData();window.__pendingRace=r;modalRoot.innerHTML=`<div class="modalBack"><div class="modal"><h2>登録確認</h2><p class="small">この内容で登録/上書きします。</p>${summaryHtml(r)}<div class="btnRow"><button class="btn" onclick="REVAPP.registerConfirmed()">登録</button><button class="btn gray" onclick="REVAPP.closeModal()">閉じる</button></div></div></div>`;}
function registerConfirmed(){const tagged=RC&&RC.applyTags?RC.applyTags(window.__pendingRace):window.__pendingRace;const r=S.upsert(tagged);closeModal();app.innerHTML=`<div class="notice"><b>${S.esc(r.date)} ${S.esc(r.place)} ${S.esc(r.raceNo)} ${S.esc(r.raceName)} 登録完了</b></div>`+detailHtml(r);unlock();window.scrollTo(0,0);}
function horseName(r,no){const h=r.horses.find(x=>+x.no===+no);return h?h.name:'';}
function resultView(r){const x=S.normalizeResult(r.result||{});const finish=(label,arr)=>arr.filter(Boolean).map(no=>`<div>${label} ${S.esc(no)} ${S.esc(horseName(r,no))}</div>`).join('')||`<div>${label} 未入力</div>`;const bet=(label,arr)=>arr.filter(v=>v.combo||v.pay).map(v=>`<div class="resultLine">${label} ${S.esc(v.combo||'')}　${S.esc(v.pay||'')}</div>`).join('')||`<div class="resultLine">${label} 未入力</div>`;return `<div class="resultLine">${finish('1着',x.firsts)}${finish('2着',x.seconds)}${finish('3着',x.thirds)}</div><hr>${bet('馬連',x.umarens)}${bet('ワイド',x.wides)}${bet('3連複',x.sanrenpukus)}`;}
function horseTable(r){return `<div class="tableWrap"><table><thead><tr><th>印</th><th>枠</th><th>馬番</th><th>馬名</th><th>単勝</th><th>人気</th><th>前走</th><th>前2</th><th>前3</th></tr></thead><tbody>${r.horses.map(h=>`<tr><td>${S.esc(h.mark)}</td><td>${S.esc(S.frameOf(h.no,r.headcount))}</td><td>${S.esc(h.no)}</td><td>${S.esc(h.name)}</td><td>${S.esc(h.odds)}</td><td>${S.esc(h.popularity)}</td><td>${S.esc(h.past1)}</td><td>${S.esc(h.past2)}</td><td>${S.esc(h.past3)}</td></tr>`).join('')}</tbody></table></div>`;}
function predictionView(r){const p=P.predictions(r);const item=(name,vals)=>`<div class="resultLine">${name}：${S.esc(vals.join(' / ')||'なし')}</div>`;return `<h2>予想</h2><div class="resultLine">判定：<b>${S.esc(p.judge)}</b></div><div class="resultLine">軸：<b>${p.axis?S.esc(`${p.axis.no} ${p.axis.name}`):'なし'}</b></div>${item('馬連（1点）',p.umaren)}${item('ワイド（3点）',p.wide)}${item('3連複（1点）',p.sanrenpuku)}`;}
function analysisHtml(r){return `<div class="analysisList">${P.analysisLines(r).map(x=>`<div class="resultLine">${S.esc(x)}</div>`).join('')}</div>`;}
function detail(id){const r=S.byId(id);if(!r){app.innerHTML='<div class="card err">レースが見つかりません</div>';return;}app.innerHTML=detailHtml(r);unlock();window.scrollTo(0,0);}
function detailHtml(raw){const r=P.recalc(raw);return `<div class="split"><div><h1>${S.esc(r.date)} ${S.esc(r.place)} ${S.esc(r.raceNo)}</h1><div class="raceTitle">${S.esc(r.raceName)}</div></div><button class="btn gray" onclick="REVAPP.showSearch()">検索へ</button></div><div class="card"><h2>基本</h2><div class="meta">${S.esc(r.grade)} / ${S.esc(r.surface)} / ${S.esc(r.distance)} / ${S.esc(r.condition)} / ${S.esc(r.age)} / ${S.esc(r.sex)} / ${S.esc(r.headcount)}頭</div>${predictionView(r)}</div><div class="card"><h2>結果</h2>${resultView(r)}</div><div class="card"><h2>予想分析</h2>${analysisHtml(r)}</div><div class="card"><h2>出馬表</h2>${horseTable(r)}</div><div class="btnRow"><button class="btn light" onclick="REVAPP.showInput('${S.esc(r.id)}')">編集</button><button class="btn gray" onclick="REVAPP.home()">トップへ</button><button class="btn red" onclick="REVAPP.askDelete('${S.esc(r.id)}')">削除</button></div>`;}
function analysis(id){const r=S.byId(id);if(!r)return;app.innerHTML=`<div class="split"><h1>予想分析</h1><button class="btn gray" onclick="REVAPP.detail('${S.esc(id)}')">詳細へ</button></div><div class="card">${analysisHtml(r)}</div>`;unlock();window.scrollTo(0,0);}
function rulePage(){app.innerHTML=`<div class="split"><h1>予想ルール</h1><button class="btn gray" onclick="REVAPP.home()">トップへ</button></div><div class="card"><h2>現在の予想ルール</h2><div class="resultLine">◎＝ライン発生源。軸ではなく、5系への接続を見る。</div><div class="resultLine">5系＝5・14・15・5枠。軸候補の本体。</div><div class="resultLine">隣＝的中導線。±1を重視。</div><div class="resultLine">買い目固定：馬連1点、ワイド3点、3連複1点。</div><div class="resultLine">勝負：◎複数、5系軸、中穴帯、1人気の固さが弱いレース。</div><div class="resultLine">見送り：対象外条件、◎○▲が1頭のみ、軸不明、軸2人気以内、5系接続弱い。</div><div class="btnRow"><button class="btn blue" onclick="REVAPP.validationPage()">検証結果</button></div></div>`;unlock();}
function multiOptions(id,label,vals){return `<div class="field"><label>${label}</label><select id="${id}" multiple size="${Math.min(vals.length,4)}">${vals.map(v=>`<option value="${S.esc(v)}">${S.esc(v)}</option>`).join('')}</select><div class="small">複数選択可</div></div>`;}
function selected(id){return Array.from(document.getElementById(id)?.selectedOptions||[]).map(o=>o.value);}
function validationPage(){app.innerHTML=`<div class="split"><h1>検証結果</h1><button class="btn gray" onclick="REVAPP.home()">トップへ</button></div>
<div class="card">
  <div class="small">検証条件は基本情報の項目名に統一し、予想ルールカテゴリーは入口・除外条件を除いた項目だけ追加します。入口・除外条件は既存の基本検索項目で判定します。</div>
  <div class="grid2">
    <div class="field"><label>検索開始日</label><input id="vFrom" type="date"></div>
    <div class="field"><label>検索終了日</label><input id="vTo" type="date"></div>
    ${multiOptions('vJudge','判定', ['勝負','見送り'])}
    ${multiOptions('vPlace','開催地', S.JRA_PLACES)}
    <div class="field"><label>レース名</label><input id="vRaceName" placeholder="例：桜花賞"></div>
    ${multiOptions('vGrade','グレード', ['G1','G2','G3','OP','特別','1勝','2勝','3勝'])}
    ${multiOptions('vSurface','馬場', ['芝','ダ','障'])}
    <div class="field"><label>距離</label><input id="vDistance" placeholder="例：1600 / 1600m"></div>
    <div class="field"><label>条件</label><input id="vCondition" placeholder="例：定量 / ハンデ"></div>
    <div class="field"><label>年齢</label><input id="vAge" placeholder="例：3歳 / 4歳以上"></div>
    <div class="field"><label>性別</label><input id="vSex" placeholder="例：牝馬 / 混合"></div>
    <div class="field"><label>頭数</label><input id="vHeadcount" type="number" min="1" max="18" placeholder="例：18"></div>
    ${(RC?.RULE_CATEGORIES||[]).map(c=>RC.selectHtml('v_'+c.key,c)).join('')}
  </div>
  <div class="btnRow"><button class="btn blue" onclick="REVAPP.validationRun()">検証開始</button></div>
</div><div id="validationResults"></div>`;validationRun();unlock();}function validationRun(){const cond={from:$('#vFrom')?.value||'',to:$('#vTo')?.value||'',judges:selected('vJudge'),places:selected('vPlace'),raceName:$('#vRaceName')?.value||'',grades:selected('vGrade'),surfaces:selected('vSurface'),distance:$('#vDistance')?.value||'',condition:$('#vCondition')?.value||'',age:$('#vAge')?.value||'',sex:$('#vSex')?.value||'',headcount:$('#vHeadcount')?.value||''};(RC?.RULE_CATEGORIES||[]).forEach(c=>{cond[c.key]=selected('v_'+c.key);});const all=S.load();const stats=ST.calc(all,cond);$('#validationResults').innerHTML=`<div class="card"><h2>的中率 / 回収率</h2>${ST.html(stats)}</div><div class="card"><h2>検証結果ランキング</h2><div class="small">現在の検索条件を基準に、予想ルールカテゴリー別の回収率・的中率をランキング表示します。</div>${ST.validationRankingHtml(all,cond)}</div><div class="card"><h2>期間比較</h2><div class="small">検索開始日・検索終了日あり：選択期間と直前同期間を比較。未指定：年別比較。</div>${ST.periodCompareHtml(all,cond)}</div>`;}
function askDelete(id){const r=S.byId(id);modalRoot.innerHTML=`<div class="modalBack"><div class="modal"><h2>削除確認</h2><p>${S.esc(r?`${r.date} ${r.place} ${r.raceNo} ${r.raceName}`:id)} を削除しますか？</p><div class="btnRow"><button class="btn red" onclick="REVAPP.deleteRace('${S.esc(id)}')">削除</button><button class="btn gray" onclick="REVAPP.closeModal()">閉じる</button></div></div></div>`;}
function deleteRace(id){S.deleteById(id);closeModal();showSearch();}
window.REVAPP={home,showInput,showSearch,searchRun,detail,analysis,rulePage,validationPage,validationRun,confirmInput,registerConfirmed,closeModal,addRow,delRow,addFinish,addBet,askDelete,deleteRace};
window.addEventListener('error',e=>{console.error(e.error||e.message);if(app&&!app.innerHTML.trim())app.innerHTML='<div class="card err">表示エラーが発生しました。</div><button class="btn" onclick="REVAPP.home()">トップへ</button>';unlock();});
home();
})();
